import type { ChangeEvent } from "react";
import { useState, useEffect } from "react";
import { type NextPage } from "next";
import Head from "next/head";
// import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [param, setParam] = useState<string | null>(null);
  const [isRadio, setIsRadio] = useState<number>(1);
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const { isLoading, data } = trpc.example.createOne.useQuery();

  const fetchTest = async () => {
    try {
      const reqURL = `http://localhost:3000/api/example/${param}`;
      console.log("calling endpoint: ", reqURL);
      const res = await fetch(reqURL, {
        method: isRadio === 1 ? "GET" : "POST",
      });
      console.log(res.json());
    } catch (error) {
      console.log("catched in trycarch");
    }
  };

  const handleRadioChange = (event: ChangeEvent<HTMLInputElement>) => {
    setIsRadio(+event.currentTarget.value);
  };

  const handleParamChange = (event: ChangeEvent<HTMLInputElement>) => {
    const input = event.target.value;
    if (input) {
      setParam(input);
    }
  };

  console.log(isRadio === 1 ? "GET" : "POST");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{hello.data?.greeting}</h1>
        <input
          type="text"
          placeholder="enter query param"
          onChange={handleParamChange}
        />
        <ul>
          <li>
            <input
              type="radio"
              value="1"
              id="GET"
              checked={isRadio === 1}
              onChange={handleRadioChange}
            />
            <label htmlFor="1">GET</label>
          </li>
          <li>
            <input
              type="radio"
              value="2"
              id="POST"
              checked={isRadio === 2}
              onChange={handleRadioChange}
            />
            <label htmlFor="2">POST</label>
          </li>
        </ul>
        <button onClick={fetchTest}>fetch</button>

        <div>
          {isLoading && <p>creating one example...</p>}
          {data && <p>{JSON.stringify(data)}</p>}
        </div>
      </main>
    </>
  );
};

export default Home;
